openapi: "3.0.0"
info: 
  version: "1.0.0"
  title: ssuckServer API
  description: "ssuckmate server API 입니다."

servers: 
  - url: http://localhost:3000/v2
    description: Local Server
  - url: http://52.78.214.64:3000/v2
    description: dev Server
paths:
  /user:
    get:
      tags:
        - "user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        '200':
          description: "모든 유저의 리스트입니다."
          content:
            $ref: '#/contents/userArray'
  /user/auth/join:
    post:
      tags:
        - auth
      summary: Create a student
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password: 
                  type: string
                name:
                  type: string
                phoneNum:
                  type: string
                dormitoryCode:
                  type: integer
      responses:
        '201':
          description: "New user is created"
          content:
            $ref: '#contents/postResponseContent'
        '409':
          description: "duplicated email"
          content:
            $ref: '#contents/postResponseContent'
  /user/auth/login:
    get:
      tags:
        - "auth"
      summary: "Login for student"
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password: 
                  type: string
      responses:
        '200':
          description: "Sucessfully logined"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: "Invaild email or password"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /sagam/auth/join:
    post:
      tags:
        - "auth"
      summary: "Create for sagam"
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password: 
                  type: string
                name:
                  type: string
      responses:
        '201':
          description: "New sagam is created"
          content:
            $ref: '#contents/postResponseContent'
        '409':
          description: "duplicated email"
          content:
            $ref: '#contents/postResponseContent'
  /sagam/auth/login:
    post:
      tags:
        - "auth"
      summary: "Login for sagam"
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password: 
                  type: string
      responses:
        '200':
          description: "Sucessfully logined"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: "Invaild email or password"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /sagam/dormitory/add:
    post:
      tags:
        - "dormitory"
      summary: "Add dormitory related to sagam (identifier is dormitory's password)"
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                name: 
                  type: string
                identifier:
                  type: string
      responses:
        '201':
          description: "New dormitory is created"
          content:
            $ref: '#contents/postResponseContent'
        '409':
          description: "duplicated name"
          content:
            $ref: '#contents/postResponseContent'
  /sagam/dormitory/join:
    post:
      tags:
        - "dormitory"
      summary: "Join existing dormitory related to sagam"
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                name: 
                  type: string
                identifier:
                  type: string
      responses:
        '201':
          description: "Joined sucessfully"
          content:
            $ref: '#contents/postResponseContent'
        '400':
          description: "Incorrect name or identifier"
          content:
            $ref: '#contents/postResponseContent'
  /sagam/parcel/add:
    post:
      tags:
        - "parcel"
      summary: "Add parcel"
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                sender: 
                  type: string
                recipient:
                  type: string
      responses:
        '201':
          description: "New parcel is added"
          content:
            $ref: '#contents/postResponseContent'
  /sagam/user:
    get:
      tags:
        - "sagam"
      summary: "기숙사의 유저 리스트 받아오기"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                userId: 
                  type: integer
      responses:
        '200': 
          description: "기숙사의 유저 리스트를 받아왔습니다."
          content:
            $ref: '#/contents/userArray'

                  

  /user/parcel/myParcels:
    get:
      tags:
        - "parcel"
      summary: "Load my parcels"
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        '200':
          description: "Display parcel list"
          content:
            $ref: '#contents/parcelArray'
  /user/parcel/changeStatus:
    put:
      tags:
        - "parcel"
      summary: "parcel상태를 찾아감,보관중,분실 중 하나로 설정"
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                id:
                  type: integer
                status:
                  type: string
      responses:
        '201':
          description: "Parcel 상태 변경 완료"
          content:
            $ref: '#contents/putResponseContent'
  /user/parcel/delete:
    delete:
      tags:
        - "parcel"
      summary: "delete parcel"
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                id:
                  type: integer
      responses:
        '201':
          description: "Parcel 삭제 완료"
          content:
            $ref: '#contents/deleteResponseContent'

  # /user/parcel/changeStatus:
  #   put:
  #     tags:
  #       - "parcel"
  #     summary: "parcel상태를 찾아감,보관중,분실 중 하나로 설정"
  #     requestBody: 
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               token:
  #                 type: string
  #               id:
  #                 type: integer
  #               status:
  #                 type: string
  #     responses:
  #       '201':
  #         description: "Parcel 상태 변경 완료"
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 message:
  #                   type: string
  # /user/parcel/delete:
  #   delete:
  #     tags:
  #       - "parcel"
  #     summary: "delete parcel"
  #     requestBody: 
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               token:
  #                 type: string
  #               id:
  #                 type: integer
  #     responses:
  #       '201':
  #         description: "Parcel 삭제 완료"
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 message:
  #                   type: string

contents:
  putResponseContent:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
  deleteResponseContent:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
  postResponseContent:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
  userArray:
    applications/json:
      schema:
        $ref: '#schemas/userArray'
  parcelArray:
    applications/json:
      schema:
        $ref: '#schemas/parcelArray'
  parcel: 
    applications/json:
        schema:
          $ref: '#schemas/parcel'
schemas:
  userArray:
    type: array
    items:
      $ref: "#schemas/user"
  user:
    type: object
    properties:
      id:
        type: integer
        example: 1
      email:
        type: string
        format: email
        example: mail@mail.com
      password:
        type: string
        example: sf23#$@$1f
      name:
        type: string
        example: userName
      phoneNum:
        type: integer
        example: 01012341234
      provider:
        type: string
        example: local
      snsId:
        type: string
      isAuthed:
        type: boolean
      penalty:
        type: integer
        example: 5
      advantage:
        type: integer
        example: 5
      createdAt:
        type: 
      room:
        type: integer
        example: 401
      dormitory:
        type: integer
        example: 1
  parcelArray:
    type: array
    items:
      $ref: "#schemas/parcel"
  parcel:
    type: object
    properties:
      id:
        type: integer
        example: 1
      sender:
        type: string
        example: 김현수
      status:
        type: string
        enum:
          - 찾아감
          - 보관중
          - 분실됨
      taker:
        type: string
        example: userName
      advantage:
        type: integer
        example: 5
      deletedAt:
        type: date-time
      room:
        type: integer
        example: 401
      dormitory:
        type: integer
        example: 1
